Implementing basic scanner code to load tokens into array
Currently stuck due to some error

```
error[E0308]: mismatched types
  --> src/scanner/scanner.rs:74:28
   |
74 |         self.tokens.append(token);
   |                            ^^^^^ expected mutable reference, found struct `Token`
   |
   = note: expected mutable reference `&mut Vec<&'code Token<'code>>`
                         found struct `Token<'_>`
```

creating a reddit post to get help with this error